### Tutorial 1&2: Understanding DataArray and Dataset objects and manipulations

Xarray is an open-source package developed especially for analyzing climate datasets. There are two data "types" here:

1. DataArray: This is a N-D (3D) array that can have metadata such as description about the contents of the array, such as names/descriptions etc. The dimensions also have names assigned to them.

2. Dataset: Dataset is like a pandas dataframe where each column is a DataArray

[link](https://comptools.climatematch.io/tutorials/W1D1_ClimateSystemOverview/student/W1D1_Tutorial1.html)

In [1]:
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
import seaborn as sns

#### DataArray object

In [2]:
tempdat = 283 + np.random.randn(3,2,4,2)
# tempdat

In [3]:
temperature = xr.DataArray(tempdat, dims = ["date", "lat", "lon", "height"])
temperature

<xarray.DataArray (date: 3, lat: 2, lon: 4, height: 2)>
array([[[[282.8882958 , 281.5609714 ],
         [283.50171906, 281.75054047],
         [284.03255091, 283.62420071],
         [283.98225364, 281.50292319]],

        [[284.04973298, 282.63499604],
         [280.28773137, 284.67718912],
         [281.79705291, 282.76254352],
         [284.90049265, 283.0686614 ]]],


       [[[283.00008458, 283.26036782],
         [282.39266098, 283.6176974 ],
         [281.13479779, 283.59927246],
         [282.6837487 , 282.50174604]],

        [[283.52306637, 283.90225429],
         [282.92583603, 283.92764397],
         [282.63351644, 284.28491647],
         [282.69580245, 282.37545489]]],


       [[[283.01807905, 283.3401651 ],
         [282.43194818, 282.87826881],
         [283.69653469, 284.73886859],
         [281.76739008, 282.5600091 ]],

        [[282.39743958, 282.97614438],
         [283.83577401, 282.20071779],
         [281.95928864, 283.02404972],
         [284.81092247, 283.38820457]]]])
Dimensions without coordinates: date, lat, lon, height

In [4]:
temperature.shape

(3, 2, 4, 2)

In [5]:
times = pd.date_range("2020-05-22", periods=temperature.shape[0])
lat = np.linspace(-45, 45, temperature.shape[1])
lon = np.linspace(-45, 45, temperature.shape[2])
height = np.linspace(10, 30, temperature.shape[3])

In [6]:
temperature = xr.DataArray(tempdat, coords=[times, lat, lon, height], 
                           dims =["date", "lat", "lon", "height"])
temperature.attrs["units"] = "Kelvin"
temperature.attrs["name"] = "temperature"
temperature

<xarray.DataArray (date: 3, lat: 2, lon: 4, height: 2)>
array([[[[282.8882958 , 281.5609714 ],
         [283.50171906, 281.75054047],
         [284.03255091, 283.62420071],
         [283.98225364, 281.50292319]],

        [[284.04973298, 282.63499604],
         [280.28773137, 284.67718912],
         [281.79705291, 282.76254352],
         [284.90049265, 283.0686614 ]]],


       [[[283.00008458, 283.26036782],
         [282.39266098, 283.6176974 ],
         [281.13479779, 283.59927246],
         [282.6837487 , 282.50174604]],

        [[283.52306637, 283.90225429],
         [282.92583603, 283.92764397],
         [282.63351644, 284.28491647],
         [282.69580245, 282.37545489]]],


       [[[283.01807905, 283.3401651 ],
         [282.43194818, 282.87826881],
         [283.69653469, 284.73886859],
         [281.76739008, 282.5600091 ]],

        [[282.39743958, 282.97614438],
         [283.83577401, 282.20071779],
         [281.95928864, 283.02404972],
         [284.81092247, 283.38820457]]]])
Coordinates:
  * date     (date) datetime64[ns] 2020-05-22 2020-05-23 2020-05-24
  * lat      (lat) float64 -45.0 45.0
  * lon      (lon) float64 -45.0 -15.0 15.0 45.0
  * height   (height) float64 10.0 30.0
Attributes:
    units:    Kelvin
    name:     temperature

#### Manipulation of the dataset Array does NOT preserve attributes

In [7]:
temperature = temperature *2 #- 15
temperature

<xarray.DataArray (date: 3, lat: 2, lon: 4, height: 2)>
array([[[[565.7765916 , 563.1219428 ],
         [567.00343812, 563.50108095],
         [568.06510182, 567.24840142],
         [567.96450727, 563.00584637]],

        [[568.09946595, 565.26999208],
         [560.57546273, 569.35437823],
         [563.59410581, 565.52508704],
         [569.8009853 , 566.13732279]]],


       [[[566.00016916, 566.52073565],
         [564.78532196, 567.2353948 ],
         [562.26959558, 567.19854492],
         [565.3674974 , 565.00349208]],

        [[567.04613274, 567.80450858],
         [565.85167206, 567.85528794],
         [565.26703289, 568.56983295],
         [565.3916049 , 564.75090979]]],


       [[[566.0361581 , 566.68033019],
         [564.86389636, 565.75653762],
         [567.39306938, 569.47773717],
         [563.53478016, 565.12001819]],

        [[564.79487917, 565.95228876],
         [567.67154802, 564.40143557],
         [563.91857727, 566.04809943],
         [569.62184495, 566.77640914]]]])
Coordinates:
  * date     (date) datetime64[ns] 2020-05-22 2020-05-23 2020-05-24
  * lat      (lat) float64 -45.0 45.0
  * lon      (lon) float64 -45.0 -15.0 15.0 45.0
  * height   (height) float64 10.0 30.0

#### Dataset object
A dataset object is a container for DataArrays with similar coordinates. The coordinates don't have to be the same across DataArrays to construct a Dataset object (unlike what the tutorial says) but I imagine the utility of the dataset object is limited when the individual DataArrays are different in their coordinates

In [8]:
temperature.coords

Coordinates:
  * date     (date) datetime64[ns] 2020-05-22 2020-05-23 2020-05-24
  * lat      (lat) float64 -45.0 45.0
  * lon      (lon) float64 -45.0 -15.0 15.0 45.0
  * height   (height) float64 10.0 30.0

In [9]:
pressure = xr.DataArray(np.random.normal(1, 0.01, size=(temperature.shape)), 
                        coords = temperature.coords)
pressure.attrs["units"] = "atm"
pressure.attrs["name"] = "pressure"
pressure

<xarray.DataArray (date: 3, lat: 2, lon: 4, height: 2)>
array([[[[1.01508088, 1.00784256],
         [1.00487495, 1.0226369 ],
         [0.99202823, 0.99054611],
         [1.00074443, 1.01229116]],

        [[1.00645773, 0.99507619],
         [1.00493113, 1.01071452],
         [0.9891202 , 0.99926555],
         [1.00761295, 0.99227166]]],


       [[[0.99342011, 0.99555976],
         [0.99714563, 0.9974656 ],
         [1.00937424, 1.00957417],
         [0.97890201, 0.99707671]],

        [[0.98499453, 1.00152655],
         [0.99753249, 1.00869064],
         [1.00422591, 0.98908981],
         [1.00007867, 0.98995289]]],


       [[[0.98239881, 0.99024808],
         [1.00195552, 1.00452369],
         [1.00607254, 1.00996133],
         [1.01901372, 0.98110115]],

        [[1.00865022, 0.99945469],
         [1.00138404, 1.00303667],
         [0.99546416, 0.98450355],
         [0.98067709, 1.00633939]]]])
Coordinates:
  * date     (date) datetime64[ns] 2020-05-22 2020-05-23 2020-05-24
  * lat      (lat) float64 -45.0 45.0
  * lon      (lon) float64 -45.0 -15.0 15.0 45.0
  * height   (height) float64 10.0 30.0
Attributes:
    units:    atm
    name:     pressure

In [10]:
info = xr.Dataset(data_vars = {"Temperature": temperature, "Pressure": pressure})
info

<xarray.Dataset>
Dimensions:      (date: 3, lat: 2, lon: 4, height: 2)
Coordinates:
  * date         (date) datetime64[ns] 2020-05-22 2020-05-23 2020-05-24
  * lat          (lat) float64 -45.0 45.0
  * lon          (lon) float64 -45.0 -15.0 15.0 45.0
  * height       (height) float64 10.0 30.0
Data variables:
    Temperature  (date, lat, lon, height) float64 565.8 563.1 ... 569.6 566.8
    Pressure     (date, lat, lon, height) float64 1.015 1.008 ... 0.9807 1.006

#### Can individual dataArrays in a Dataset have different coordinates and/or dimensions?

In [11]:
humidity = xr.DataArray(np.random.normal(50, 10, size=(3,2,3)))
info["humidity"] = humidity

In [12]:
info

<xarray.Dataset>
Dimensions:      (date: 3, lat: 2, lon: 4, height: 2, dim_0: 3, dim_1: 2, dim_2: 3)
Coordinates:
  * date         (date) datetime64[ns] 2020-05-22 2020-05-23 2020-05-24
  * lat          (lat) float64 -45.0 45.0
  * lon          (lon) float64 -45.0 -15.0 15.0 45.0
  * height       (height) float64 10.0 30.0
Dimensions without coordinates: dim_0, dim_1, dim_2
Data variables:
    Temperature  (date, lat, lon, height) float64 565.8 563.1 ... 569.6 566.8
    Pressure     (date, lat, lon, height) float64 1.015 1.008 ... 0.9807 1.006
    humidity     (dim_0, dim_1, dim_2) float64 64.67 70.33 46.84 ... 56.21 47.2

#### Data selection and slicing

Numpy-like selection works but there are more advanced methods of selection using `sel()`, `interp()` and `loc()`

In [13]:
first_array = temperature[1,:,:]
first_array

<xarray.DataArray (lat: 2, lon: 4, height: 2)>
array([[[566.00016916, 566.52073565],
        [564.78532196, 567.2353948 ],
        [562.26959558, 567.19854492],
        [565.3674974 , 565.00349208]],

       [[567.04613274, 567.80450858],
        [565.85167206, 567.85528794],
        [565.26703289, 568.56983295],
        [565.3916049 , 564.75090979]]])
Coordinates:
    date     datetime64[ns] 2020-05-23
  * lat      (lat) float64 -45.0 45.0
  * lon      (lon) float64 -45.0 -15.0 15.0 45.0
  * height   (height) float64 10.0 30.0

In [16]:
first_array = temperature.sel(date="2020-05-23")
first_array

<xarray.DataArray (lat: 2, lon: 4, height: 2)>
array([[[566.00016916, 566.52073565],
        [564.78532196, 567.2353948 ],
        [562.26959558, 567.19854492],
        [565.3674974 , 565.00349208]],

       [[567.04613274, 567.80450858],
        [565.85167206, 567.85528794],
        [565.26703289, 568.56983295],
        [565.3916049 , 564.75090979]]])
Coordinates:
    date     datetime64[ns] 2020-05-23
  * lat      (lat) float64 -45.0 45.0
  * lon      (lon) float64 -45.0 -15.0 15.0 45.0
  * height   (height) float64 10.0 30.0

In [19]:
interpolated_temp = temperature.sel(date="2020-05-24", method="nearest")
interpolated_temp

<xarray.DataArray (lat: 2, lon: 4, height: 2)>
array([[[566.0361581 , 566.68033019],
        [564.86389636, 565.75653762],
        [567.39306938, 569.47773717],
        [563.53478016, 565.12001819]],

       [[564.79487917, 565.95228876],
        [567.67154802, 564.40143557],
        [563.91857727, 566.04809943],
        [569.62184495, 566.77640914]]])
Coordinates:
    date     datetime64[ns] 2020-05-24
  * lat      (lat) float64 -45.0 45.0
  * lon      (lon) float64 -45.0 -15.0 15.0 45.0
  * height   (height) float64 10.0 30.0

In [28]:
temperature.sel(date=slice("2020-05-22", "2020-05-24"), 
                lon=slice(-40,4),
                lat = slice(-20,10)
               )

<xarray.DataArray (date: 3, lat: 0, lon: 1, height: 2)>
array([], shape=(3, 0, 1, 2), dtype=float64)
Coordinates:
  * date     (date) datetime64[ns] 2020-05-22 2020-05-23 2020-05-24
  * lat      (lat) float64 
  * lon      (lon) float64 -15.0
  * height   (height) float64 10.0 30.0

In [29]:
temperature.sel(lon=slice(-40,4),
                date=slice("2020-05-22", "2020-05-24"), 
                
               )

<xarray.DataArray (date: 3, lat: 2, lon: 1, height: 2)>
array([[[[567.00343812, 563.50108095]],

        [[560.57546273, 569.35437823]]],


       [[[564.78532196, 567.2353948 ]],

        [[565.85167206, 567.85528794]]],


       [[[564.86389636, 565.75653762]],

        [[567.67154802, 564.40143557]]]])
Coordinates:
  * date     (date) datetime64[ns] 2020-05-22 2020-05-23 2020-05-24
  * lat      (lat) float64 -45.0 45.0
  * lon      (lon) float64 -15.0
  * height   (height) float64 10.0 30.0

Same thing can be done with loc but without specifying the names and has to be in the right order

In [31]:
temperature.loc["2020-05-22":"2020-05-24", -40:40]

<xarray.DataArray (date: 3, lat: 0, lon: 4, height: 2)>
array([], shape=(3, 0, 4, 2), dtype=float64)
Coordinates:
  * date     (date) datetime64[ns] 2020-05-22 2020-05-23 2020-05-24
  * lat      (lat) float64 
  * lon      (lon) float64 -45.0 -15.0 15.0 45.0
  * height   (height) float64 10.0 30.0